### ISSUE TITLE
Estimated Runtime

### ISSUE THREAD

**Issue by Quinncuatro** [piersdeseilligny/betterfountain#1]
I have a title page and one scene (one page) written and my runtime says 19:01:10.

It started at 19:00:00 when I hadn't written anything.

Absolutely love this extension otherwise, but do you have any idea what's going on?

**Comment by piersdeseilligny** [comment]
That's really weird... Does it only happen with a screenplay in particular, or all the time? Unless it's the latter, could you share the problematic screenplay?

**Comment by Quinncuatro** [comment]
All .fountain files. Defaults to starting at 19 hours.

**Comment by Quinncuatro** [comment]
Updated VS Code to version 1.28.2 and it's still having the issue. Not a BIG deal in the grand scheme of things, though.

**Comment by Quinncuatro** [comment]
Been looking through that extension file you pointed to in the other issue. The durationStatus code looks really simple. I have no idea where it's getting that 19 value for the hour.

**Comment by Quinncuatro** [comment]
Actually, think I found a fix. Working on something in JSfiddle.

Your `var time = new Date(null);` command is defaulting to the Unix epoch time. With my timezone (-5 hours), it's defaulting the hours field to 19.

**Comment by piersdeseilligny** [comment]
Fixed in release 1.1.1
