### ISSUE TITLE
Broken layout for dual dialogue if "Print dual dialogue in two columns" is disabled

### ISSUE THREAD

**Issue by TipiT** [piersdeseilligny/betterfountain#100]
I have a script where two characters are talking at the same time,  “dual dialogue,” so the text blocks should go side-by-side. I'm not able to get that working and it should be possible using a caret ^.

https://fountain.io/syntax#section-dual

**Comment by piersdeseilligny** [comment]
@TipiT Thanks for the feedback! Could you send a sample text/screenshot of the situation in which it's not working? I can't seem to reproduce the issue. Does it still not work, even with a very simple example? For example, this:
```
ALICE
Hello

BOB^
Hi
```
Should look like this in the live preview:

![image](https://user-images.githubusercontent.com/42496508/102139059-3bb82c00-3e55-11eb-808a-7cc24b129088.png)

And this in the PDF:
![image](https://user-images.githubusercontent.com/42496508/102139238-7b7f1380-3e55-11eb-82f7-21ae04437499.png)

**Comment by TipiT** [comment]
Hi @piersdeseilligny! It's not working in my script, so I made a blank project with same results.

Editor:
<img width="470" alt="Screenshot 2020-12-14 at 23 24 59" src="https://user-images.githubusercontent.com/1223414/102143192-dfa8d400-3e63-11eb-91db-d659279e921d.png">

Live preview - Notice that it actually intents the Bob! Even adds a one line break after the name.
<img width="528" alt="Screenshot 2020-12-14 at 23 25 15" src="https://user-images.githubusercontent.com/1223414/102143186-dc154d00-3e63-11eb-8bb5-9c1665c1e6c7.png">

Exported .PDF
<img width="560" alt="Screenshot 2020-12-14 at 23 24 39" src="https://user-images.githubusercontent.com/1223414/102143194-e0416a80-3e63-11eb-9d09-043dd773a486.png">

**Comment by piersdeseilligny** [comment]
That's *very* odd. Could you please send me the .fountain file of that blank example so I can take a closer look?

**Comment by TipiT** [comment]
That's the exact file. I had  to .zip it, because .fountain files are not accepted. :)

[example.fountain.zip](https://github.com/piersdeseilligny/betterfountain/files/5694043/example.fountain.zip)

**Comment by piersdeseilligny** [comment]
I still can't seem to reproduce this issue, although I've added a new command to BetterFountain 1.7.3, which might help resolve this:
![image](https://user-images.githubusercontent.com/42496508/102216495-25e94c00-3ed3-11eb-913c-07ded6ff55da.png).

Could you send me the JSON running that command generates, with that same example you sent?

**Comment by TipiT** [comment]
I only have 1.7.2 available, so I'll wait for the new release.

**Comment by piersdeseilligny** [comment]
@TipiT sorry there was a typo in my previous message! the "Debug parsed output" command is included in 1.7.2

**Comment by TipiT** [comment]
I got 1.8 installed, but I still cannot find the "Debug parsed output". Not in the settings or in the commands list. So how do I run the command?

**Comment by piersdeseilligny** [comment]
@TipiT normally it should show up in the command palette, by pressing `Ctrl+Shift+P` or `F1`:

[![Image from Gyazo](https://i.gyazo.com/24ceda66952deb06b19d93972379c27b.gif)](https://gyazo.com/24ceda66952deb06b19d93972379c27b)

**Comment by TipiT** [comment]
There you go!

[debug-json.txt](https://github.com/piersdeseilligny/betterfountain/files/5879139/debug-json.txt)

PDF output:

[example.pdf](https://github.com/piersdeseilligny/betterfountain/files/5879166/example.pdf)

**Comment by piersdeseilligny** [comment]
Thanks! I have to say this is an extremely confusing bug. In addition to the files you just sent, could you send the `.fountain` file too @TipiT ?

**Comment by TipiT** [comment]
Renamed to .txt.
[example.fountain.txt](https://github.com/piersdeseilligny/betterfountain/files/5905293/example.fountain.txt)

Yes, I agree, because it almost works. :) Maybe you can give me a .fountain file that works, so I can test it? Maybe the issue is me or my old Mac.

**Comment by piersdeseilligny** [comment]
I don't understand this at all haha
![image](https://user-images.githubusercontent.com/42496508/106492823-4a63ac80-64b0-11eb-8f83-da2619b2d77c.png)

What versions of macOS and vscode are you using?

**Comment by TipiT** [comment]
MAC OS X: 10.15.7
vscode: 1.52.1 - No updates available

Updated MAC to: 11.2 - Nothing changed.
Reinstalled the extension - No luck.

**Comment by TipiT** [comment]
Can you attach a functional .fountain file that works in your setup?

**Comment by piersdeseilligny** [comment]
[test.fountain.txt](https://github.com/piersdeseilligny/betterfountain/files/5926178/test.fountain.txt)

Well the issue is that the one you sent me seems to work fine - although here's another, which works fine on my side. This is the parsed output:

```json
{
    "title_page": [],
    "tokens": [
        {
            "text": "INT. HOUSE - DAY",
            "type": "scene_heading",
            "start": 0,
            "end": 17,
            "line": 0,
            "number": "1",
            "takeNumber": -1
        },
        {
            "text": "",
            "type": "separator",
            "start": 18,
            "end": 18,
            "line": 1,
            "takeNumber": -1
        },
        {
            "type": "dual_dialogue_begin",
            "takeNumber": -1
        },
        {
            "text": "ALICE",
            "type": "character",
            "start": 19,
            "end": 25,
            "line": 2,
            "dual": "left",
            "takeNumber": 1
        },
        {
            "text": "Hello",
            "type": "dialogue",
            "start": 26,
            "end": 32,
            "line": 3,
            "dual": "left",
            "time": 0.324258,
            "character": "ALICE",
            "takeNumber": -1
        },
        {
            "text": "BOB",
            "type": "character",
            "start": 34,
            "end": 39,
            "line": 5,
            "dual": "right",
            "takeNumber": 2
        },
        {
            "text": "Hi",
            "type": "dialogue",
            "start": 40,
            "end": 43,
            "line": 6,
            "dual": "right",
            "time": 0.1297032,
            "character": "BOB",
            "takeNumber": -1
        },
        {
            "type": "dual_dialogue_end",
            "takeNumber": -1
        }
    ],
    "scriptHtml": "",
    "titleHtml": "",
    "lengthAction": 0,
    "lengthDialogue": 0.45396119999999995,
    "tokenLines": {
        "1": 1,
        "2": 3,
        "3": 4,
        "4": 6,
        "5": 5,
        "6": 7
    },
    "properties": {
        "sceneLines": [
            0
        ],
        "scenes": [
            {
                "scene": "1",
                "line": 0,
                "actionLength": 0,
                "dialogueLength": 0
            }
        ],
        "sceneNames": [
            "INT. HOUSE - DAY"
        ],
        "titleKeys": [],
        "firstTokenLine": 0,
        "fontLine": -1,
        "lengthAction": 0,
        "lengthDialogue": 0,
        "characters": {},
        "structure": [
            {
                "text": "INT. HOUSE - DAY",
                "children": null,
                "range": [
                    {
                        "line": 0,
                        "character": 0
                    },
                    {
                        "line": 0,
                        "character": 16
                    }
                ],
                "id": "/0"
            }
        ]
    }
}
```

I don't really expect it to work on your side, given what you sent me didn't work, but it's worth a short I guess 🤷‍♂️

**Comment by TipiT** [comment]
It did not work...

Still indents the person with the ^ correctly and ads an empty line...

<img width="589" alt="Screenshot 2021-02-04 at 17 01 09" src="https://user-images.githubusercontent.com/1223414/106919811-c5280400-670a-11eb-9442-02100db99364.png">

I though maybe it has something to do with text encoding or something. But I guess that is not the case either. First one is yours:

➜  file test.fountain 
test.fountain: ASCII text, with CRLF line terminators
➜  file testme.fountain 
testme.fountain: ASCII text

I have currently no other ideas how to debug the issue. You? :)

**Comment by piersdeseilligny** [comment]
@TipiT oh my, i think I may have finally figured this out. If you go in the settings, is this disabled by any chance?

![image](https://user-images.githubusercontent.com/42496508/107556953-ea1beb80-6bd0-11eb-91d8-c9c9a4537f7e.png)

**Comment by TipiT** [comment]
It was not and enabling it solved the issue!

So it was not a bug, but a feature/setting. I don't understand the use for this, so is there a justification for the setting? Or should it just be always enabled?

Thank you very much @piersdeseilligny !

**Comment by piersdeseilligny** [comment]
Glad that fixed it! it's a setting "left over" by afterwriting, which the PDF renderer was based off. I have to admit that it's not very useful - I might remove it, although it normally should be enabled by default, so it might make more sense to just fix the layout when it's disabled.

**Comment by TipiT** [comment]
OK, finally the mystery solved. Great job @piersdeseilligny !
