### ISSUE TITLE
Can't be installed from marketplace

### ISSUE THREAD

**Issue by shaedrich** [piersdeseilligny/betterfountain#107]
Hey Piers,

I can't install this extension from the marketplace. When I search it in vscode, it doesn't show up. The only way, I could install it, is via vsix. Am I the only one with that problem and am I doing something wrong or might this be a bug?

Thanks in advance!
Sebastian

**Comment by piersdeseilligny** [comment]
@shaedrich Thanks for the bug report! That's definitely very odd.. It seems to be working on my side, by simply searching for "fountain", even on a fresh version of vscode:

![image](https://user-images.githubusercontent.com/42496508/104769902-eaf36600-5767-11eb-897a-9d31e6ebd49f.png)

I pushed an update yesterday, it might be some weird behaviour on Microsoft's side of things?

**Comment by piersdeseilligny** [comment]
@shaedrich still running into this issue?

**Comment by tamuratak** [comment]
See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by piersdeseilligny** [comment]
@tamuratak I published betterfountain to OpenVSX a few days ago, so normally it should show up now, regardless of platform - presumably this issue can be closed then?

**Comment by tamuratak** [comment]
I think it can be closed.
