### ISSUE TITLE
Live Preview - Opening Titles not displayed correctly/

### ISSUE THREAD

**Issue by bilbo50** [piersdeseilligny/betterfountain#108]
Hi,
In the well-known "Brick and Steel" Fountain Sample Script (from https://fountain.io), at about Line 97, there are "Opening Titles".  In Live Preview, these lines don't seem to be displayed correctly. (The PDF Export of this .fountain file works correctly.)

I attach 3 .png files.  1) The BF/VSC listing of the .fountain file is on the left; the Live Preview of the  "Opening Titles" is on the right.
2) The PDF Export of this .fountain file.  3) As a comparison, the same .fountain file as imported into and rendered by the FadeIn program

Thanks for all your hard work!

![Visual Studio Code - Opening Titles in Fountain   Live Preview - Brick   Steel](https://user-images.githubusercontent.com/36517797/105400260-4f8c4600-5bea-11eb-9b19-956539a0193d.PNG)
![Better Fountain - Visual Studio Code -- Opening Titles - Brick   Steel - PDF Export](https://user-images.githubusercontent.com/36517797/105400397-7b0f3080-5bea-11eb-9f99-73a785dda479.PNG)
![FadeIn - Opening Titles - Brick   Steel](https://user-images.githubusercontent.com/36517797/105400527-abef6580-5bea-11eb-9c86-7b4e3a32f5fb.PNG)

**Comment by piersdeseilligny** [comment]
Thank you for reporting this! I'il look into it more closely tomorrow and will push an update with a fix asap.

**Comment by piersdeseilligny** [comment]
@bilbo50 I've just released 1.8.1, which is available now and should fix this issue:

![image](https://user-images.githubusercontent.com/42496508/105567941-b9613880-5d2d-11eb-8ca1-f6100b9193c7.png)

Thanks again for reporting it!

**Comment by bilbo50** [comment]
Hi Piers, 

Glad to help, and that it seems not to have been a difficult fix for you. The "Brick and Steel" .fountain example for download (https://fountain.io/syntax) seems to have been on the Fountain website for years, so I thought I should report it. 

Those 4 lines of "Opening Titles" don't seem to me to be formatted/composed as REAL titles--I mean, "in" should be on its own line, right? But I see their purpose is to be merely illustrative of Fountain formatting (centering text). 

I have two .fountain files that I've made my own Fountain "test bed": The "Brick and Steel" .fountain example, and the latest Academy of Motion Picture Arts and Sciences "sample script" (for their screenwriting fellowships) available for download: https://www.oscars.org/nicholl/screenwriting-resources (under the "FORMATTING TIPS" tab). I put the .pdf file through a ".pdf to .txt" program first, and then manually edited (e.g., stripped out "MORE"s & "cont'd"s) the resulting mess into a proper .fountain file. 

Additional Fountain syntax elements: The first thing I noticed about the "formal"-looking Academy sample was that it lacked Dual Dialogue. So I added my own (my FIRST original!) scene, with DD, as a new final scene. (As a test, I also made a variation with 6 simultaneous speakers). Finally reading the entire Fountain Syntax section on its website, I found more elements that could be added to test. The slightly "rough-and-tumble" "Brick and Steel" .fountain example was shorter, so I decided to add them there. Here they are, in the order I added them: 

1) Indentation of text in "Action" elements 

2) A Series of Shots, and 
3) Italics, bolding, and underlining of text 
(& combinations thereof) 

4) Song lyrics 

5) A true Montage script format (as compared to 2) above) 
(I only stumbled across this recently in The Screenwriter's Bible 6th ed.) 

In case these files might be of any use to you, I'm attaching them. 


------------------------- 

P.S. I think I noticed that there was an open ticket that Dual Dialogue wasn't working for that user. Having just applied your latest BF update, I checked DD--both Dual and 6-person dialogue. Working fine for me--both "Live Preview" and "Exported PDF". Assuming the user didn't simply miss a caret, I wonder (based on my own past mistakes) if there might be a hidden character somewhere--best to delete & retype that Dual Dialogue portion of the text? 

Cheers 

Bilbo50 
Dave Knezetich 


----- Original Message -----

**Comment by piersdeseilligny** [comment]
Yeah the fountain.io website tends to be a little outdated, it's not really maintained very much anymore. And that .fountain file you're mentioning actually sounds really useful! However I don't think you can send attachments through GitHub email responses, would you mind uploading it somewhere else? And yeah you're right about the dual-dialogue, I think the issue is probably something along those lines.

**Comment by bilbo50** [comment]
Sure. 

Do you have a Google account? Is that possible or would that work for you? In anticipation, I've already uploaded them to my Google Drive storage--I could share them with you (I guess I would need your Google ID or email or something) (I do almost 0% file sharing or uploading!) 

P.S. RE: the Academy script sample download, I did not convert the cover sheet from .PDF to Fountain. 

dave 


----- Original Message -----
