### ISSUE TITLE
Publish Extension on Open VSX Registry

### ISSUE THREAD

**Issue by ghost** [piersdeseilligny/betterfountain#109]
Sorry if this isn't the right place to suggest this, but is it possible to publish this extension on https://open-vsx.org/ as well as the VS Code marketplace? This would let [VS Codium](https://vscodium.com/) users access the extension as well. There is very little difference between VS Code and Codium as Code is a fork of Codium, so it shouldn't require any additional coding. There is a guide on how to add an extension to Open VSX [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by piersdeseilligny** [comment]
[Done :)](https://open-vsx.org/extension/piersdeseilligny/betterfountain)
