### ISSUE TITLE
Betterfountain 1.8.1 not working

### ISSUE THREAD

**Issue by viegasfh** [piersdeseilligny/betterfountain#114]
Hi!

I am having issues processing Betterfountain 1.8.1. Everything just fails, from outline to rendering.

I am including the log files I got from the developer tools.

I hope you can sort this out.

Thanks!
[-1612594045892.log](https://github.com/piersdeseilligny/betterfountain/files/5936394/-1612594045892.log)
[-1612594060839.log](https://github.com/piersdeseilligny/betterfountain/files/5936395/-1612594060839.log)
[-1612594076584.log](https://github.com/piersdeseilligny/betterfountain/files/5936396/-1612594076584.log)
[-1612594083143.log](https://github.com/piersdeseilligny/betterfountain/files/5936397/-1612594083143.log)
[-1612594100481.log](https://github.com/piersdeseilligny/betterfountain/files/5936398/-1612594100481.log)

**Comment by piersdeseilligny** [comment]
@viegasfh thank you so much for reporting this! What's the last version which works correctly? You can right-click on the extension in the extensions pane (Ctrl+Shift+X) and select "Install another version"

**Comment by viegasfh** [comment]
Hi, Pierse!

Version 1.8.0 was and is still working fine. I don't really keep track of the updates, but noticed this error yesterday. I reverted back to 1.8.0.  Thanks!

**Comment by viegasfh** [comment]
Piers,

I think it might be something in Visual Studio Code that broke the plugin. None of them are working now. It may have been some update.

**Comment by piersdeseilligny** [comment]
So I can't manage to consistently reproduce this issue. On the latest version of vscode (1.53.0) I was able to reproduce it for a bit, but then mid-way through debugging it, it stopped occurring.
However purely based off the logs you sent, I did a few small changes which may fix it, although I'm not at all sure it will work. If you update to this recently published version of betterfountain (1.8.2), are you still running into this issue?

**Comment by viegasfh** [comment]
Hi, Piers!

It is working on my laptop with the latest update of VS Code 1.5.3. Need to test it on my main PC. Will come back with feedback. Thanks!

**Comment by viegasfh** [comment]
Hi again, Piers!

Unfortunatelly on my Desktop computer it still gives me some errors and I can't figure out why. I am attaching the logs.
[-1612927235671.log](https://github.com/piersdeseilligny/betterfountain/files/5955663/-1612927235671.log)
[-1612927251406.log](https://github.com/piersdeseilligny/betterfountain/files/5955664/-1612927251406.log)
[-1612927262726.log](https://github.com/piersdeseilligny/betterfountain/files/5955665/-1612927262726.log)
[Uploading -1612927267734.log…]()

**Comment by piersdeseilligny** [comment]
@viegasfh I have to admit this is a very confusing bug, and slightly worrying if you're not the only one getting it (which I'm assuming you're not). What happens if you try to run it in a completely clean untouched version of vscode? Such as the [Insider release](https://code.visualstudio.com/insiders/) (which you can install alongside the regular one)?

**Comment by viegasfh** [comment]
Hi, Piers!

Let me give it a try and come back to you with more feedback.

**Comment by piersdeseilligny** [comment]
@viegasfh are you still running into this issue?

**Comment by viegasfh** [comment]
Hi, Piers!

Sorry for the delay. I have updated to the latest version 1.8.3 and it is working without any issues. Did you manage to find out what was causing the issue?

**Comment by piersdeseilligny** [comment]
I think it may have been a bug in vscode, although it's hard to tell. Glad it's fixed though!
