### ISSUE TITLE
Tab key used to trigger smart autocomplete

### ISSUE THREAD

**Issue by stephenberry** [piersdeseilligny/betterfountain#116]
I really like the autocomplete after `Enter->Enter`, but I'm finding myself often needing to trigger it with `Backspace->Enter`, because I've deleted my original thought.

It would be great if the tab key could be used to trigger autocomplete, since tab isn't a part of the Fountain syntax anyway. Just a minor convenience request. Thanks for your work!

**Comment by stephenberry** [comment]
Oh, I guess Action does respect tabs in the fountain specification.

**Comment by piersdeseilligny** [comment]
Normally `Ctrl+Space` (or `Cmd+Space` on macOS I believe?) should trigger it, let me know if that works :)

**Comment by stephenberry** [comment]
Thanks, `Ctrl+Space` on macOS works. That's a good alternative. Feel free to close this issue.
