### ISSUE TITLE
Live Preview should scale to fit

### ISSUE THREAD

**Issue by benthillerkus** [piersdeseilligny/betterfountain#12]
Right now there are horizontal scroll bars which is pretty annoying.

**Comment by piersdeseilligny** [comment]
I'm too bad at css to correctly fix this, but I've improved the structure of the app to make it easier if someone else wants to help. [This](https://github.com/piersdeseilligny/betterfountain/blob/master/client/src/webview.html) is the relevant file.

**Comment by benthillerkus** [comment]
From my also pretty basic CSS knowledge, I'd assume that it's this hardcoded width at [line 295](https://github.com/piersdeseilligny/betterfountain/blob/9c459d2003071c87f96d6caf0f62c12d9f3dc7a3/client/src/webview.html#L295)
For the scaling something like [this](https://css-tricks.com/scaled-proportional-blocks-with-css-and-javascript/) should probably be done. I have no clue how anything in Visual Studio Code & Typescript etc works though
