### ISSUE TITLE
non-bold scene headings

### ISSUE THREAD

**Issue by NQNStudios** [piersdeseilligny/betterfountain#124]
People in my workshop keep pointing out that the scene headings of my pages are bold when they don't need to be. Is there a setting to have slug lines non-bold?

**Comment by piersdeseilligny** [comment]
of course :) if you go in the vscode settings, you can disable `Embolden Scene Headers`:

![image](https://user-images.githubusercontent.com/42496508/114317195-dae8e980-9afe-11eb-9054-2b2447d84cee.png)

There's a bunch of other settings in there too which you might find useful!
