### ISSUE TITLE
Feature Request: Toggle what marks are shown in outline view with persistent setting

### ISSUE THREAD

**Issue by kortina** [piersdeseilligny/betterfountain#127]
I was thinking about reasons why I go to use Highland 2 over VS Code + Better Fountain when working on screenplays, and I think one of the main things I like about the former is the ability to get a navigator with synpses and headers (instead of scene heading slugs):

![image](https://user-images.githubusercontent.com/5924/116491987-05051000-a850-11eb-8fad-a5783d70596f.png)

It would be awesome (and probably not terribly hard) to implement something similar in Better Fountain.

Perhaps could be implemented as settings:

```jsonc
"fountain.outline.sections": true|false,
"fountain.outline.synopses": true|false,
"fountain.outline.sceneHeaders": true|false,
"fountain.outline.notes": true|false,
```

**Comment by piersdeseilligny** [comment]
@kortina thanks, that's definitely a good idea! I came up with a slightly different approach, which will hopefully make it as easy to toggle as it is in Highland:
[![Demo gif](https://i.gyazo.com/e8bc72f289b43a0807a82dc94c2eb2ff.gif)](https://gyazo.com/e8bc72f289b43a0807a82dc94c2eb2ff)

It's a lot less janky than the previous toggling system - will hopefully release it soon :)

**Comment by piersdeseilligny** [comment]
Included as part of 1.8.4, now live in the marketplace :)

**Comment by kortina** [comment]
Very excited to try this out!

OK, so strange, I updated and got 1.8.4 but don't have thee buttons from your screenshot:

![image](https://user-images.githubusercontent.com/5924/116824758-b225a400-ab40-11eb-8feb-8f0de27a72e3.png)

Do I need to enable them somehow?

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.4.0
```

![image](https://user-images.githubusercontent.com/5924/116824800-e8fbba00-ab40-11eb-8394-c7ae28f454ac.png)

Was there maybe an issue with the public build not including some feature flag?

**Comment by piersdeseilligny** [comment]
@kortina that outline is only the built-in vscode one, you can access the more feature-rich one in the "BetterFountain" panel, on the left-hand side :)
![image](https://user-images.githubusercontent.com/42496508/116825355-e754e500-ab86-11eb-8714-3fff2cc91f96.png)
