### ISSUE TITLE
Option to turn off auto complete

### ISSUE THREAD

**Issue by jeffk529** [piersdeseilligny/betterfountain#129]
Love all the work you've done on this - thank you, thank you! Was wondering if you could add an option to turn off the auto complete (for character cues and scene headings). It works very well, but sometimes I just like to write distraction-free, even if it means more keystrokes. Thanks for considering.

**Comment by jeffk529** [comment]
One other fairly simple thing that I've enjoyed with another Fountain-based app (Highland, I think) is a key binding to SHIFT+ENTER, which (1) transforms the entire current line to ALL CAPS - and (2) does a hard return to the next line. Nice for scene headings and character cues if one forgets to tap the caps lock beforehand. Thanks again for considering.

**Comment by piersdeseilligny** [comment]
Hi @jeffk529 and thank you for the kind words :) I was actually starting to implement this feature after reading this issue, but then realized it's already possible to disable suggestions in vscode, you can simply disable the (`editor.suggestOnTriggerCharacters`) setting:

![image](https://user-images.githubusercontent.com/42496508/117590584-1f7c9a80-b128-11eb-9bbb-6ee686c73491.png)

If you want, you can then still trigger autocomplete with `Ctrl+Space`.

Also, if you want to make this setting only affect `fountain` documents, you can edit the JSON settings as such:
![image](https://user-images.githubusercontent.com/42496508/117590669-8306c800-b128-11eb-9d81-623d0228b775.png)

Please let me know if this solves the problem, and if so i'il close the issue :)

**Comment by jeffk529** [comment]
Thanks so much for your response. I will definitely try that and let you
know.

Jeff

Sent from my Android tablet. Please excuse the brevity.

------
Jeff Keller
240-315-3550 (voice/text)
***@***.***

**Comment by jeffk529** [comment]
Couldn't find the Json file. The first method didn't work completely and I
tried several others. I think it was disabling this one that did the trick..

[image: image.png]

Jeff
