### ISSUE TITLE
Feature Request: Address the workspaces restrictions recently introduced in VSCode

### ISSUE THREAD

**Issue by shauryashaurya** [piersdeseilligny/betterfountain#135]
When I opened VSCode today to write, the BetterFountain button had disappeared. Upon further troubleshooting (uninstall the extension, reinstall) the application performed a trust check - if I trust the workspace to execute the code. 
This may mean, either parts of our code are incompatible, or that it may need to perform additional steps to ensure trust. 
Maybe worth looking into?

**Comment by piersdeseilligny** [comment]
@shauryashaurya this should be fixed in the latest release (1.8.5) :)
