### ISSUE TITLE
Underlined Scene Headings do not work in preview

### ISSUE THREAD

**Issue by thegreentimtam** [piersdeseilligny/betterfountain#140]
The following scene heading:

`._FLASHBACK:_ EXT. COUNTRY ROAD - DAY`

is syntax highlighted as a CHARACTER in the editor, shown as a scene heading with underscores in the live preview, and exported as a correctly formatted scene heading (with FLASHBACK: underlined) in the PDF output.

**Comment by piersdeseilligny** [comment]
Thanks for the bug report @thegreentimtam ! Definitely not normal behaviour - will investigate and publish a fix asap.

**Comment by piersdeseilligny** [comment]
Fixed in 1.8.10, which is currently live in both the vscode marketplace and open-vsx :)
