### ISSUE TITLE
Intellisense in Github Repositories

### ISSUE THREAD

**Issue by c0din** [piersdeseilligny/betterfountain#141]
Is possible to add Intellisense suggestions/autocomplete to the Github Repositories extension? It doesn't seem to work when editing a script in the virtual environment.

**Comment by piersdeseilligny** [comment]
@c0din thanks a lot for reporting this, and sorry for the delay in getting back to you. I've just published an updated version (1.8.9) which should fix this - can you let me know if it works better for you now?

**Comment by c0din** [comment]
@piersdeseilligny it's working perfectly. This was such a minor issue, but thank you for the response. I really enjoy the simplicity of writing in vscode, so thank you so much for making this extension!
