### ISSUE TITLE
1 tab and 4 spaces does not have the same size in the PDF

### ISSUE THREAD

**Issue by geueds** [piersdeseilligny/betterfountain#149]
In the following excerpt, considering 4 spaces = 1 tab,

```
!SUPERIMPOSE: **DAY ONE, SCENE ONE**
             SOMETHING BAD'S ABOUT TO HAPPEN

!SUPERIMPOSE: **DAY ONE, SCENE ONE**
			 SOMETHING BAD'S ABOUT TO HAPPEN
```

The alignment is not the same, as seen here:

![image](https://user-images.githubusercontent.com/21070088/147281952-541f345f-4322-4261-921b-f8f79e690bd0.png)

**Comment by piersdeseilligny** [comment]
Fixed by 1.9.0, currently live in the marketplace :)
