### ISSUE TITLE
Help with "Show Live Preview" : Blacked out text from cut off point. 

### ISSUE THREAD

**Issue by Reverie02** [piersdeseilligny/betterfountain#151]
![VSC HELP](https://user-images.githubusercontent.com/97303142/148572140-fdbd360f-7ee0-4968-adee-e29bc904f41e.png)

This has started to happen today, uninstalled and reinstalled but still happens.

Any advice?

**Comment by piersdeseilligny** [comment]
Thanks for reporting this! I'il publish a fix to this asap, but in the meantime you can make it more readable by switching to the vscode theme rather than the paper one:

![image](https://user-images.githubusercontent.com/42496508/148652829-c9e90264-c164-412a-b68e-b16ee921ed66.png)

**Comment by Reverie02** [comment]
Many thanks.

**Comment by piersdeseilligny** [comment]
@Reverie02 I've just published version 1.9.1 of the extension, which should have fixed this with the paper theme too :)
