### ISSUE TITLE
FEATURE REQUEST: Page Headers for Episodic Shows

### ISSUE THREAD

**Issue by datatimp** [piersdeseilligny/betterfountain#156]
REQUEST: Customizable page headers for scripts that require it, like episodic shows. 

Common elements include:
- Show name justified left (sometimes in bold)
- Episode #
- Episode Name
- Date

Their is no one single header format as needs of shows vary, but all of these elements would need to be inserted, removed or altered as needed.

The page number still prints justified right. 

Example header [here](https://imgur.com/a/2d3tcR4).

**Comment by piersdeseilligny** [comment]
Thanks for this feature request, would something similar to the "tl" "tc" or "tr" title page keys work? 

Something along the lines of "hl" (Header-left), "hc" (Header-center) and "hr" (Header-right) which could specify text to be inserted into the header of each page. So the title page section could look something like:

```
Title: Spaghetti Junction Episode 2
Credit: written by
Author: John Smith
hl: **SPAGHETTI JUNCTION**
hc: "Storage Wars" 
```

Can you foresee any potential issues with that?

**Comment by datatimp** [comment]
> Thanks for this feature request, would something similar to the "tl" "tc" or "tr" title page keys work?
> 
> Something along the lines of "hl" (Header-left), "hc" (Header-center) and "hr" (Header-right) which could specify text to be inserted into the header of each page. So the title page section could look something like:
> 
> ```
> Title: Spaghetti Junction Episode 2
> Credit: written by
> Author: John Smith
> hl: **SPAGHETTI JUNCTION**
> hc: "Storage Wars" 
> ```
> 
> Can you foresee any potential issues with that?

I think adding some keys into the metadata at the top of the document is smart. I can't foresee any conflicts off the top of my head. Perhaps controlling the number of empty lines after the header would be the only other issue. I think Trelby defaults to 1 single blank line, which is two narrow. I usually up it to 2. I'm honestly not sure if that violates a formatting standard or not.

**Comment by piersdeseilligny** [comment]
@WrinkleRelease That's it added in version 1.10.0, which should be live in the marketplace now :) You can add it with the "Header" title page key. As an example:

```
Header: **SPAGHETTI WARS**        "STORAGE WARS"
```
![image](https://user-images.githubusercontent.com/42496508/156946039-20e3c2f1-02e1-4613-abb0-08f7bc7420ca.png)

All this does is override the "Page Header" setting for a given document:

![image](https://user-images.githubusercontent.com/42496508/156946094-fc6620e2-f209-43b2-b225-2442bbfe4a42.png) 

which I'il admit I'd actually forgotten to mention earlier 👀 although 1.10.0 adds it in the live preview, and adds support for markdown-style syntax (such as `**bold**`).

While I was at it I also added the "Footer:" title page key, which does the same but... on the footer.

**Comment by datatimp** [comment]
Thanks! I just saw this!
