### ISSUE TITLE
Dark Mode for Preview

### ISSUE THREAD

**Issue by washere** [piersdeseilligny/betterfountain#16]
Hi,

Thanks for this work, I love it.

I just discovered this extension today. I think it will be important. Why?

Because Markdown is on the rise with the static/wiki generators we use (I use 7 platforms) and for those of us who do screenwriting, .fountain (different to MD) is the obvious choice. The best txt editor for coding used to be Sublime Text, then came Atom and now MS VS Code has pushed it's way to the top. So this extension will be important in future for Screenwriters, though many of them do not know of it yet!

Almost all my apps on Windows and Android (including dark Substrautm dark themes for sys) are black/dark. For a couple of decades millions of us hacked MS Windows with dark themes (thousands of themes in theming forums) by changing sys files etc. These caused problems with some apps. Finally after 20+ years MS finally extended the dark theme for apps it had released a few years ago to explorer (folder files) a few months ago. Also apps can now detect dark setting and auto switch to dark, as in a few apps already doing this.

Most coders, graphic workers, photographers, CGI Workstation staff, animators etc only use dark apps for many reasons. Pro CGI rooms even have lighting engineers who install special equipment to control the darkness levels and controls.

There are many reasons many genres of Computer workers use dark themes for apps and systems:

* Eye sensitivity
* Can Work Longer
* With less stress on the eye and brain
* No Flicker (Was worse on CRT days but still subtly there with white)
* Better precision
* Longer battery life on laptops and portable devices
etc.

So please give us the option for dark mode for preview:

**Black Background + White/Light Grey Font**

Did I say I love this extension? Thanks again.

https://www.instagram.com/worldcode/

https://www.instagram.com/programmerrepublic/

**Comment by washere** [comment]
![Light Mode](https://user-images.githubusercontent.com/5448047/54157786-ead60100-4440-11e9-96f4-8c786593531d.png)

.

![Dark Mode ](https://user-images.githubusercontent.com/5448047/54157801-f3c6d280-4440-11e9-9a86-93a7113b6d8b.png)


.

**Comment by piersdeseilligny** [comment]
I'm going to look into this, and potentially having three different options:

* Light theme
* Dark theme
* VSCode default, where it just blends in with the currently selected theme (will make this the default)

**Comment by vekuda** [comment]
I am trying out VS Code for the first time, and I came here to request exactly this feature. 

I don't know how useful it can be to @piersdeseilligny, but I am currently using superlou's 'fountain' package (Atom) which does have this 'dark mode for preview' thing.

**Comment by piersdeseilligny** [comment]
**This will be available in 1.3.0.**

The way it's implemented is by giving the option between two themes in the extension's settings: "vscode" and "paper". "vscode" uses the colors of the current theme, while "paper" is the legacy white-background-black-foreground from 1.2

As a result, it will adapt nicely to whatever theme you currently use, light or dark:

![image](https://user-images.githubusercontent.com/42496508/56086493-1477b300-5e59-11e9-9ca2-d9395b77845c.png)
![image](https://user-images.githubusercontent.com/42496508/56086519-57398b00-5e59-11e9-8e03-28f9d1c1800d.png)
![image](https://user-images.githubusercontent.com/42496508/56086528-6d474b80-5e59-11e9-9e79-bfdf1e56c35e.png)
