### ISSUE TITLE
pdf library

### ISSUE THREAD

**Issue by pjebs** [piersdeseilligny/betterfountain#161]
Is there a library on npm where I can provide fountain data and it will generate the pdf data back?

Alternatively, how can I use the files in src/pdf directory in my own project?

**Comment by piersdeseilligny** [comment]
Hi! I don't believe so, sorry. There's [afterwriting as a command line interface](https://github.com/ifrost/afterwriting-labs/blob/master/docs/clients.md) on NPM, but not as a library.

You could indeed extract src/pdf from BetterFountain and use it as a library, but it won't work in browsers. It's also pretty heavily embedded into the rest of BetterFountain, so it'll unfortunately take a fair amount of picking apart and detangling, but it should still be possible!

The easiest way to do so would just be to download the contents of `src/pdf`, and then install libraries and add files from the rest of `src` until you have no more errors. Then you'll need to feed the `parseoutput` from `src/afterwriting-parser.ts` (which will come with it's own set of dependencies) into `GeneratePdf` from `src/pdf/pdf.ts`, along with an output path, and a config object (in `src/configloader.ts`). You'll also have to remove all the vscode-specific logic.

Unfortunately it's a bit of a mess to do all of this, but generating PDFs outside of BetterFountain has never been in the scope of the project.

**Comment by pjebs** [comment]
How come it won't work on browsers?

**Comment by piersdeseilligny** [comment]
It uses features and libraries for nodejs which aren't available in browsers.
