### ISSUE TITLE
Scene Autocomplete Broken

### ISSUE THREAD

**Issue by cyniphile** [piersdeseilligny/betterfountain#162]
Thank you very much for the extension.

Scenes aren't autocompleting with the following error:

```
[2022-03-10 14:01:03.937] [exthost] [error] TypeError: parsedDocument.properties.sceneNames[index].indexOf is not a function
    at FountainCompletionProvider.provideCompletionItems (/Users/luke/.vscode/extensions/piersdeseilligny.betterfountain-1.10.0/out/ ...
```

The root cause is the `pushSorted` prototype you've added to `Array` is indexed as part of this loop: 
https://github.com/piersdeseilligny/betterfountain/blob/9d7a9375df7ee0e42e24dbe53ecaf6b97231956b/src/providers/Completion.ts#L221

So if you have, say, two scenes, the indicies will be [0, 1, pushSorted] which causes an error in the loop body on the third and final loop. 

I'll push up a fix for the scene problem, but note that any use of `for (const i in array) {` will be broken as well, and you'll have to switch to `for (let i = 0; i < array.length; i++)`.

**Comment by piersdeseilligny** [comment]
Thank you so much for raising this and for the PR! Apologies if I've been a little slow, been very busy recently. I'il have a look at merging this in at some point in the next week.
