### ISSUE TITLE
Scroll-Sync Lock

### ISSUE THREAD

**Issue by washere** [piersdeseilligny/betterfountain#17]
Thanks for this wonder extension.

Most modern Markdown editors have Previews as a second pane/window in dual mode, Editor + Preview.

Many of the top ones have an additional feature:

Scroll-Sync Lock
or:
Sync-Scroll Lock

This basically updates the other pane as we scroll up and down the other. So as you go down the editor window pane, the preview pane also goes up/down to sync both panes.

Can we have Scroll-Sync Lock please.

It would make this extension even more fantastic.

Some apps that have this feature for MD editing are:

MS VS Code Markdown preview
ia Writer
Atom MD Preview
Joplin (For Desktop (Windows version))
QOwnNotes
etc etc.

Please lets have Scroll-Sync Lock.

Thanks again.

**Comment by piersdeseilligny** [comment]
@washere This feature has now been added! It's part of v1.6.0, which is now released. It's bidirectional and you can open the editor to any position by double-clicking somewhere.
