### ISSUE TITLE
Set the default value for fountainconfig.scenes_numbers to both.

### ISSUE THREAD

**Issue by geueds** [piersdeseilligny/betterfountain#177]
That's the way it's by default in a lot of screenplay softwares, I always have to set it to `both` when I install it in a new computer, and it would be better for people who are first joining betterfountain **and may be afraid to mess up with the extension settings, as this is the way it should be by default**.

Thanks!

**Comment by piersdeseilligny** [comment]
Fixed in 1.12.0
