### ISSUE TITLE
Jump to line returns "Illegal value for 'line'"

### ISSUE THREAD

**Issue by ThomasProbyn** [piersdeseilligny/betterfountain#180]
To reproduce: Open a fountain file and use the command pallette to jump to line. A messagebox appears/a VSCode Notification popup saying "Illegal value for 'line'"

**Comment by piersdeseilligny** [comment]
The "Jump to line" command is used internally by the extension (when clicking on items in the outline view, it is used to jump to the line of the specific item) and isn't meant to be used from the command palette. I'il remove it from there in the next version.
