### ISSUE TITLE
Web Client seems to have some issues

### ISSUE THREAD

**Issue by Asrour494** [piersdeseilligny/betterfountain#186]
It seems like the web client of VSCode has some issue with this extension. When selecting the Better Fountain icon on the left toolbar, it pulls up the headers for the three sections but just loads endlessly. Downloaded client works just fine however, so it could very well be VSCode's fault.
![image](https://user-images.githubusercontent.com/107585790/208490851-b4e82363-b980-4a68-af4e-7bd5c3181609.png)

**Comment by piersdeseilligny** [comment]
Thanks for the feedback! Unfortunately, BetterFountain isn't yet compatible with the web client, because a number of features rely on desktop-only libraries (notably those surrounding PDF rendering).

**Comment by Asrour494** [comment]
Thanks for replying!

Yeah I figured the web client was just weird.
