### ISSUE TITLE
Auto-add "(CONT'D)"

### ISSUE THREAD

**Issue by vekuda** [piersdeseilligny/betterfountain#19]
This is a nice feature - and also a divisive one, for very good reasons.

Auto-add "(CONT'D)" is an option found in Final Draft and other screenwriting processors, which automatically adds **(CONT'D)** to the character's name when he reprises a speech interrupted by a fast and significant action.

Such an option spares a lazy writer a couple of strokes, but it wouldn't work in an action-packed scene - where the lines of a character might indeed belong to very distant moments in the scene.

So the utility of this feature varies from person to person, and possibly from project to project. That's why I believe that it would be very useful to have.

**Comment by jasonmeisel** [comment]
It auto-adds the CONT'D when exporting to PDF, not in the fountain file (because that's how the fountain standard works).

It *would* be nice to show the (CONT'D) in the editor, though.

**Comment by vekuda** [comment]
Actually Amazon Storywriter displays the (CONT'D) even in the editor itself

**Comment by piersdeseilligny** [comment]
It's not really possible to add into the editor, as that would require getting the preview to have the exact same layout as the pdf export, which isn't easily doable, as the way they are rendered is completely different :/

**Comment by vekuda** [comment]
I see. Can you manage to make it work it at least on the exported PDF, though?

**Comment by rickschubert** [comment]
I agree with the sentiment that we should _not_ add this. As a writer myself, I have a script which would be negatively affected by such a feature. I prefer to set the "CONT'D" marks on my own when I see fit.
