### ISSUE TITLE
Can't export to PDF

### ISSUE THREAD

**Issue by Quinncuatro** [piersdeseilligny/betterfountain#2]
Getting the following error when I try exporting my script to PDF. The runtime issue isn't really a big deal but this is kind of annoying. Any idea what's going on here? If you can point me to the right portion of your code that handles this, I wouldn't mind helping work through the problem.

Failed to export PDF: Error: Command failed: afterwriting --source "c:\Users\henryquinn\Desktop\screenplays\TheMarriagePact\index.fountain" --pdf "c:\Users\henryquinn\Desktop\TakeTwo..pdf" --overwrite --config "c:\Users\henryquinn\Desktop\betterfountain.pdf.json" 'afterwriting' is not recognized as an internal or external command, operable program or batch file.

**Comment by piersdeseilligny** [comment]
[This](https://github.com/piersdeseilligny/betterfountain/blob/master/client/src/extension.ts#L279) is the relevant line. 

The export to PDF function relies on an npm package called [afterwriting](https://www.npmjs.com/package/afterwriting). It's marked as a dependency in the extension's [package.json](https://github.com/piersdeseilligny/betterfountain/blob/master/package.json#L230), so normally it should get installed with the extension.

I'm pretty new to node.js and typescript, so I'm gonna assume i'm doing something really stupid. Any help is indeed welcome :)

**Comment by Quinncuatro** [comment]
I'll start looking into it. Are you able to export your .fountain files to PDF?

**Comment by Quinncuatro** [comment]
Worked when I ran `npm install -g afterwriting`.

I wonder why it didn't work "out of the box." I'll close this one since I'm set, but I'll see if I can't duplicate the issue on another computer tomorrow.

**Comment by piersdeseilligny** [comment]
Ok so it turns out this issue isn't fixed, i'm going to try and directly integrate the required tools from afterwriting into the extension, to avoid all of this somewhat hacky cli stuff.

**Comment by shazron** [comment]
`npm install` is not run for a vscode extension: https://github.com/Microsoft/vscode/issues/23300#issuecomment-290341502

But if you `vsce` pack it after running `npm install`, it should be included (unless specifically excluded in `.vscodeignore`)

Instead of using a globally pathed `afterwriting`, in your activation handler (where you call the `afterwriting` cli) get the absolute path to your bundled `./node_modules/afterwriting/awc.js` and substitute your call to `afterwriting` with that.

Before (pseudocode):
```javascript
exec(`afterwriting --source <other_options_here>...`)
```

After (pseudocode):
```javascript
let afterwritingPath = context.asAbsolutePath(path.join('node_modules', 'afterwriting', 'awc.js'))
exec(`node ${afterwritingPath} --source <other_options_here>...` )
```

I haven't had a chance to test it yet and/or send a PR...

**Comment by piersdeseilligny** [comment]
Thanks a lot! However the problem with this is that although vscode is built on electron (and so nodejs) node isn't actually installed "system-wide" when you just install vscode (I think? I'm not super knowledgeable about how electron and nodejs work). Regardless, running `exec('node')` won't work on a clean install of vscode+betterfountain.

Unfortunately I think the only option to get this working "out of the box" is completely integrating afterwriting into betterfountain :/

**Comment by Quinncuatro** [comment]
Found your next sprint, @piersdeseilligny. ^^lol

**Comment by shazron** [comment]
@piersdeseilligny You're right about node.  Perusing the `afterwriting` code, it seems *simple* (famous last words! haha) since the code is basically in https://github.com/ifrost/afterwriting-labs/blob/master/js/client/client-controller.js

**Comment by piersdeseilligny** [comment]
@shazron yup, simple until you run into `protoplast` everywhere, which is a custom library written by the dev of afterwriting with zero documentation :/

**Comment by piersdeseilligny** [comment]
Work on integrating afterwriting is being done on the [feature/afterwriting](https://github.com/piersdeseilligny/betterfountain/tree/feature/afterwriting) branch.

**Comment by shazron** [comment]
Thanks for this work! Much appreciated

**Comment by piersdeseilligny** [comment]
I sent an email about afterwriting to Piotr Jamróz (the author), and basically the only way to correctly integrate afterwriting into betterfountain is to completely extract the logic to a separate library.

Therefore, the plan is to make fountain-js (powering the live preview) as good as afterwriting at parsing fountain, and then use the tokens obtained for the live preview to create the pdf, reusing code from afterwriting.

Gonna remove the breaking changes from the `feature/afterwriting` branch, merge the smaller ones to master, and simultaneously work on the pdf export in `feature/pdf` and improve fountain-js in `master`.

**Comment by shazron** [comment]
@piersdeseilligny thanks for this, makes sense. If you have architected this out and you need assistance writing some parts, let me know!

**Comment by piersdeseilligny** [comment]
@shazron will do :) I'm still busy figuring out how exactly this is gonna work, but i'il let you know if I need help.

The current plan has changed since my last message: I'm going to replace the fountain-js parser with a port of the afterwriting one ([just here](https://github.com/piersdeseilligny/betterfountain/blob/feature/newparser/client/src/afterwriting-parser.ts)), which is actually way better designed.

That requires slightly rewriting the way the html is obtained from the tokens, but it will be significantly easier to add the pdf export code from afterwriting once that's done. Also, consistency between the live preview and the rendered pdf is kind of a good thing.

**Comment by Quinncuatro** [comment]
Do you have a Patreon or something? I'd love to throw you $1/month for this.

**Comment by piersdeseilligny** [comment]
@Quinncuatro Thanks a lot! I don't have a Patreon, but I just added a "Support via PayPal" button to README.md

**Comment by Quinncuatro** [comment]
@piersdeseilligny What kind of percentage is PayPal taking?

**Comment by piersdeseilligny** [comment]
@Quinncuatro It depends on where you are, any currency conversion involved, and if you're paying by debit/credit or via a paypal balance/linked bank account. From what I can tell, it can be anywhere between 0% and 4%, which is still less than the 5% that Patreon takes.

**Comment by piersdeseilligny** [comment]
So I've successfully ported the pdf export functionality from afterwriting right into this extension in the `feature/newparser` branch. The only problem left to figure out is error handling when exporting the PDF.

**Comment by Quinncuatro** [comment]
@piersdeseilligny - https://github.com/sponsors

**Comment by piersdeseilligny** [comment]
@Quinncuatro I know this is almost a year-old thread, but thanks for letting me know about that! My Github sponsors profile has been accepted, so it's now an option for anyone wishing to support this project.
