### ISSUE TITLE
old/dead link in the extensions marketplace page

### ISSUE THREAD

**Issue by gargolito** [piersdeseilligny/betterfountain#218]
The extension page has an information link to a page that doesn't exist, the current link is:

https://piersdeseilligny.com/work/everything-else/betterfountain/

I think it should be:
https://piersdeseilligny.com/work/software/betterfountain/

**Comment by piersdeseilligny** [comment]
Thanks for flagging this! Absolutely right - I updated my website but haven't yet updated the vscode listing.
