### ISSUE TITLE
Some characters do not appear in "locations"

### ISSUE THREAD

**Issue by nkat29** [piersdeseilligny/betterfountain#222]
E.g. if the line is "EXT. MÖTLEY CRÜE - DAY", in the locations part it shows "Mtley Cre". Outline part works correctly, it shows the line exactly as it is (all uppercase).

Interestingly, when the character's name is "MÖTLEY CRÜE", it shows the name correctly with title case (Mötley Crüe).

**Comment by piersdeseilligny** [comment]
Fixed in 1.14.1, which should be live in the store very shortly :)
