### ISSUE TITLE
= synopsis syntax results in unwanted carrier returns in PDF output

### ISSUE THREAD

**Issue by ghost** [piersdeseilligny/betterfountain#26]
Per fountain.io, = denoted syntax text should not be rendered in the output. While the Synopsis text is invisible, it seems to consistently insert an unwanted carrier return in the PDF output resulting in apparent typos.

**Comment by ghost** [comment]
Checked afterwriting.com as I know this is the source of the PDF export code. It does *not* appear to generate this error with the same fountain file. Hopefully that's helpful.

**Comment by piersdeseilligny** [comment]
Fixed in 1.3.1 (currently in the store)

**Comment by ghost** [comment]
Awesome. Thanks for this great work, Piers! The script I wrote with it made it through the first round of the Sundance Episodic lab. 😊
