### ISSUE TITLE
Draft date not in PDF export

### ISSUE THREAD

**Issue by jpyams** [piersdeseilligny/betterfountain#27]
# Steps to Reproduce
Create a fountain screenplay that includes in the title page section:

    Draft date: 04/20/2019

Export the screenplay to a PDF.  (there's nothing special about this particular date, it's just an example).

# Issue
The draft date is not included on the title page.

The draft date does appear in the live preview in VS Code, just not in the exported PDF.

**Comment by piersdeseilligny** [comment]
Fixed in 1.3.1 (currently in the store)
