### ISSUE TITLE
No scene numbers in exported pdf

### ISSUE THREAD

**Issue by hevonen** [piersdeseilligny/betterfountain#31]
I can't get page numbers to show in exported pdf.

According to fountain syntax it should be something like:
INT. KITCHEN SINK #1#
and
EXT. FIELD #2.1#

Are these unsupported or am I doing something wrong? I looked and there seems to be some flags in afterwriting package related to scene numbering.

**Comment by piersdeseilligny** [comment]
Sorry for the late reply! This does work, but you need to enable it in the settings (`Settings` > `Fountain PDF Export`). You can choose to have the scene numbers either on the left, on the right, or both.

I'm going to change the default behavior and improve consistency between the live preview and the exported pdf.

**Comment by hevonen** [comment]
Excellent, thanks!

**Comment by rickschubert** [comment]
To add, pull request #43 relates to this which allows the user to have the scenes automatically numbered (either each time they save or when triggering the command from the command pallette).
