### ISSUE TITLE
Forced scene headers are scoped and highlighted as numbers

### ISSUE THREAD

**Issue by zoltair** [piersdeseilligny/betterfountain#32]
Forcing a scene header by starting the line with a period (.) causes the whole line to be scoped as `constant.numeric.scene.fountain` instead of `keyword.other.class`. I propose replacing the scene heading regular expression (on line 265 of fountain.tmlanguage) with this instead:
```xml
<string>(?i)^([.](?=[0-9a-z])|(?:[*]{0,3}_?)(?:int|ext|est|int[.]?\/ext|i[.]?\/e)[. ])(.+?)(#[-.0-9a-z]+#)?$</string>
```

That scopes the scene header the same whether it starts with a period or with "INT", "EXT", etc. As a bonus, it also scopes a trailing scene number (alphanumeric characters surrounded by hash signs) as `constant.numeric.scene.fountain`, which I assume was the intent at some point.

**Comment by piersdeseilligny** [comment]
Fixed in 1.4.0, currently live in the marketplace
