### ISSUE TITLE
Ability to turn off noise texture in Live Preview

### ISSUE THREAD

**Issue by the-moonwitch** [piersdeseilligny/betterfountain#40]
Hi,

Thank you for making this extension, it's the best way to edit Fountain I've found. However, I find the noise texture in the live preview very distracting - could we get an option to toggle it off?

Thanks once again.

**Comment by piersdeseilligny** [comment]
This has been added to version 1.4.3, which is now live in the marketplace :) 

You should now be able to disable the noise texture by switching off the `fountain.pdf.previewTexture` setting.

![image](https://user-images.githubusercontent.com/42496508/63793588-42d5c680-c900-11e9-9870-9b5919676186.png)
