### ISSUE TITLE
Setting that automatically appends scene numbers (exported PDF and scene outline)

### ISSUE THREAD

**Issue by rickschubert** [piersdeseilligny/betterfountain#41]
When the setting is correctly enabled, one can use scene numbers (such as `INT. HOUSE - DAY #1#`) to manually number headings.

I would find it useful if there would be an additional feature that numbers all the scenes automatically, both for the PDF export as well as for the scene outline.

**Comment by rickschubert** [comment]
Note: Perhaps I will have take on this feature next weekend myself, but I am not promising anything.

**Comment by rickschubert** [comment]
I just wanted to confirm that I am actually already working on this. I will create a command which will automatically number the scenes. Thus, this will also work on the exported PDF.

Displaying the scene numbers in the scene outline is a different feat, which I will not tackle (yet).

I will perhaps also create a setting where the user can decide whether the scenes should be numbered everytime they save the document.

**Comment by osomfinch** [comment]
Rick, there is a bug now that won't export the scene numbers to PDF; they are not in live preview as well. Is there a way to fix that issue?
