### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by asterox** [piersdeseilligny/betterfountain#5]
Seems as though use of this extension disables word wrapping settings in the editor.

Despite changing to "bounded" and column wrap of 80, the fountain content wraps to the viewport.

**Comment by piersdeseilligny** [comment]
The extension sets specific word-wrapping settings for fountain files, to make them easier to read. However, you can override this by adding fountain-specific settings in your `settings.json` file:

```json
"[fountain]": {
        "editor.wordWrap": "bounded",
        "editor.wordWrapColumn": 80
    }
```

**Comment by asterox** [comment]
Thanks!

**Comment by asterox** [comment]
Is there a way to get the live preview to ignore boneyard items marked with /* ?

H

**Comment by piersdeseilligny** [comment]
Boneyard isn't yet supported by the live preview, so currently not :/ Maybe you could create a new issue for this, so that people who want to contribute are aware of this issue?

**Comment by asterox** [comment]
Will do. Did you ever do any of this work for Atom or Sublime Text by the way?

**Comment by piersdeseilligny** [comment]
Nope, but the base of the .tmlanguage file of the extension (for syntax highlighting) is based off the one in [this](https://github.com/poritsky/fountain-sublime-text) extension for sublime text.
