### ISSUE TITLE
Autocomplete is going haywire

### ISSUE THREAD

**Issue by RalphORama** [piersdeseilligny/betterfountain#52]
I just installed the extension, and I'm having trouble with the autocomplete.  No matter where I am in a document, it wants to autocomplete fields for the title page. 

**VS Code Info:**
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Installed Plugins:**
- Angular Snippets 8.3.0
- Better Fountain 1.4.3
- Code Spell Checker 1.7.20
- ESLint 2.0.14
- Gruvbox Themes 1.0.0
- Material Theme Icons 1.1.3
- Python 2020.1.58038
- Remote - WSL 0.41.7
- Remote VSCode 1.1.0

**Examples:**

![image](https://user-images.githubusercontent.com/6566104/72647169-dfe3db00-3945-11ea-9da4-30f20981f164.png)
![image](https://user-images.githubusercontent.com/6566104/72647202-f9852280-3945-11ea-8524-59da2c1b3b9a.png)
![image](https://user-images.githubusercontent.com/6566104/72647240-115ca680-3946-11ea-9669-6aaf97d7d9cb.png)

**Comment by piersdeseilligny** [comment]
Odd, i can't reproduce this bug on my side, same vscode version. It might be related to the other extensions you've got installed, but I'd be surprised?

The responsible line is probably [this one](https://github.com/piersdeseilligny/betterfountain/blob/master/src/extension.ts#L568), maybe something is causing the document to not be parsed correctly. Does the live preview work correctly?

**Comment by piersdeseilligny** [comment]
@RalphORama are you still having this issue? Even with all the extensions you have installed i'm unable to reproduce it.

**Comment by Croydon** [comment]
I'm having the same issue  with 1.4.3 in VS Code 1.43.2 on Windows 10

**Comment by piersdeseilligny** [comment]
@Croydon could you try setting a breakpoint on [this line](https://github.com/piersdeseilligny/betterfountain/blob/master/src/extension.ts#L568) of `extension.ts`? What's the value of `firstTokenLine`?

**Comment by piersdeseilligny** [comment]
@RalphORama @Croydon are you still running into these issues on the latest version of the extension (1.4.4)?

**Comment by Croydon** [comment]
Thanks a lot @piersdeseilligny 

Version 1.4.4 fixed it for me 😄
