### ISSUE TITLE
Outline section not displaying any scenes

### ISSUE THREAD

**Issue by rickschubert** [piersdeseilligny/betterfountain#54]
I am not too sure whether this is a bug or whether this feature never existed. But judging from the readme it seems like this feature should work. If the feature never existed, please feel free to close this ticket.

**Expected behaviour**
When opening a fountain document
Then I should see in the "Outline" section a list of scenes

**Actual behaviour**
When opening a fountain document
Then I see in the "Outline" section the message "The active editor cannot provide outline information"

Below example screenshot is showing the Big Fish script.

![image](https://user-images.githubusercontent.com/25436915/76192377-8f685b80-61d9-11ea-9f23-57fd7d6cf6bc.png)

**Comment by piersdeseilligny** [comment]
The Outline appears in the BetterFountain tab, as such:

![image](https://user-images.githubusercontent.com/42496508/77355985-5da8d600-6d3d-11ea-9aaa-dca5730a5bf1.png)

So it's intentional, although maybe not very intuitive i'il admit :/
