### ISSUE TITLE
NAME and NAME^ are reported as two different characters in statistics

### ISSUE THREAD

**Issue by jborjon** [piersdeseilligny/betterfountain#57]
When using `^` next to a character's name for dual dialogue, that character is reported as a wholly different individual in the screenplay statistics.

Wow, what an extension. I've been using it for two days and I don't know how I could live without it before. Thank you.

**Comment by piersdeseilligny** [comment]
@jborjon I'm glad you like the extension! This should be fixed in the next release, in addition to character names followed by parentheticals not being included in the statistics.

**Comment by jborjon** [comment]
Awesome, glad to hear. Thanks, @piersdeseilligny.
