### ISSUE TITLE
Character names aren't autocompleting

### ISSUE THREAD

**Issue by Amparose** [piersdeseilligny/betterfountain#63]
Probably the most time saved would be having autocomplete work like the scenes. It is stated as a feature so I am wondering if this is a bug.

**Comment by piersdeseilligny** [comment]
@Amparose To what extent does it "not work"? Normally it should behave like this:

[![Image from Gyazo](https://i.gyazo.com/79f51d35e7ad5c9b33bca2d3b53983d4.gif)](https://gyazo.com/79f51d35e7ad5c9b33bca2d3b53983d4)

Does it happen on every fountain document or just some?

**Comment by Amparose** [comment]
Oh wow... that doesn't happen for me at all in any of my .fountain files.

Here is what I get when I press enter twice from the action line:

![image](https://user-images.githubusercontent.com/949192/85003448-82eb8b80-b156-11ea-9f3a-9682999da694.png)

**Comment by piersdeseilligny** [comment]
@Amparose Does this issue still occur if you have multiple differently named characters? I've realized there's a potential bug where there's no autocompletion if you only have a single named character in your `.fountain`.

**Comment by Amparose** [comment]
Ah you found it. It does make a difference. If I add a second character, my first character pops up. Also, I noticed that it omits the last used character name from the list. This means that a character can't have multiple lines sequentially, which is essential for comics and storyboarding.

**Comment by piersdeseilligny** [comment]
@Amparose so i've fixed this issue by slightly redesigning the way character autocompletion works. It will still suggest characters from the before-last one until the beginning of the scene first (as this makes writing dialogue between two people very fast), but it will also suggest the previous one at the end - so a scene with a single character in it will have that character as the first autocomplete choice.

This fix is part of 1.6.1, which should be live in the extension marketplace any minute now (currently "Verifying")
