### ISSUE TITLE
PDF Export Bookmarks

### ISSUE THREAD

**Issue by PixelboysTM** [piersdeseilligny/betterfountain#64]
It would be nice, when the Pdf-Export would have the Option to set a Bookmark at every new Scene.

**Comment by piersdeseilligny** [comment]
That's a really good idea! Will definitely be adding this.

**Comment by piersdeseilligny** [comment]
![image](https://user-images.githubusercontent.com/42496508/85143322-e5718400-b249-11ea-84ac-20f7615ebe1c.png)

@PixelboysTM Added :) it's included in 1.6.2, which is currently available in the extension marketplace.

There's two new settings: 
* `Create Bookmarks` enabled by default and which does as the name describes
* `Invisible Sections Bookmarks` also enabled by default, which adds bookmarks for sections, even if "Print Sections" is disabled.

**Comment by PixelboysTM** [comment]
Great I will use this a lot.👍

**Comment by PixelboysTM** [comment]
Great I will use this a lot.👍
