### ISSUE TITLE
Export to PDF broken...

### ISSUE THREAD

**Issue by boardkeystown** [piersdeseilligny/betterfountain#66]
When I export to PDF it creates a 0kb file then is missing. 

It's very weird because it was working 100% just a few days ago.

**Comment by piersdeseilligny** [comment]
@boardkeystown thanks for reporting this! it's a bug which must have been introduced in one of the last couple versions, as I tweaked the way PDF Exporting works. Does this happen for any fountain document? And could you share the betterfountain settings you're using?

**Comment by piersdeseilligny** [comment]
@boardkeystown are you still having this issue? I fixed a bug in the latest update which may have been causing this, if you had several sections in a row before the next scene, such as:

```markdown
# Act 1
## Part 1
INT. SCENE - DAY
```

**Comment by boardkeystown** [comment]
Yes I did. And now it's exports again! Thank you so much for making such a great plugin.
