### ISSUE TITLE
sourceline_(num) on preview

### ISSUE THREAD

**Issue by geueds** [piersdeseilligny/betterfountain#68]
~~Why is this happening?~~

Why is the source line appearing in the preview instead of the scene number? How can I fix it?
![image](https://user-images.githubusercontent.com/21070088/85234779-3ae29800-b3e6-11ea-813a-8d5ea86ab2a8.png)

![image](https://user-images.githubusercontent.com/21070088/85234848-c9571980-b3e6-11ea-8fef-c228e7a3794e.png)

**Comment by piersdeseilligny** [comment]
@gabrguedes Apologies, that looks like a slightly stupid bug where instead of displaying the scene numbers, the preview is displaying the `id` of the scene header. There'll be a fix published within the next hour.

**Comment by geueds** [comment]
OH, ok, I took a little time to figure it out, just edited it and you got it quite quickly.

Anyhow, I use **vscode** as my main screenwriting software thanks to your extension.

The new icon/logo for BetterFountain looks gorgeous, by the way. Great job!

**Comment by piersdeseilligny** [comment]
1.6.3 (which fixes this issue) is now live in the marketplace, so you should be able to update straight from vscode. And thank you for the kind words! The old logo was really ugly so it was quite a low bar haha - and I'm glad you're using betterfountain as your main screenwriting software, it means a lot to me! If ever you make money with the screenplays you write, please don't hesitate to sponsor the project :P
