### ISSUE TITLE
Syntax Highlighting fails on Linux

### ISSUE THREAD

**Issue by zoltair** [piersdeseilligny/betterfountain#7]
I have Visual Studio Code installed on Ubuntu 18.04. Syntax highlighting was not working and using "Inspect TM Scopes" produced an error that "no grammar provided for <text.source.fountain". But, it worked fine on my Windows 10 install.

The fix is simple. Linux filenames are case-sensitive. The syntax file is named "fountain.tmlanguage" but needs to be renamed to "fountain.tmLanguage" instead (capital "L" in "tmLanguage") to match the filename in "packages.json". Once I renamed that file manually, syntax highlighting started working.

**Comment by piersdeseilligny** [comment]
Fixed for 1.1.2 (via the package.json file :P)
