### ISSUE TITLE
[Improvement] In screenplay statistics, subtract one page to remove title page (If a title page exists)

### ISSUE THREAD

**Issue by rickschubert** [piersdeseilligny/betterfountain#71]
Given I have a screenplay
And my screenplay has 173 pages
And my screenplay has a title page
When I use the command "Calculate screenplay statistics"
Then it says that my screenplay has 174 pages
But it should say 173 pages as the title page shouldn't count

**Comment by piersdeseilligny** [comment]
This is actually already the case in the `feature-statsrevamp` branch, where both are displayed:

![image](https://user-images.githubusercontent.com/42496508/87221768-dd02f980-c36e-11ea-8047-cebab27c522f.png)

**Comment by rickschubert** [comment]
Oh, nice!
