### ISSUE TITLE
[Development Feature] Add travis CI pipeline

### ISSUE THREAD

**Issue by rickschubert** [piersdeseilligny/betterfountain#72]
Hi @piersdeseilligny ,

I would like to add a test pipeline. [I have done this before](https://github.com/rickschubert/fountain-note-taker). This pipeline would run on every pull request and run the tests. It would also run the tests on a merge to master. I think it would be a) quite useful if people add pull requests and b) give off a good impression to have some nice green ticks on every commit showing that everything is alright!

I have previously used the TravisCI plugin which is free for open-source repositories like your own and you get 100 free builds per month. I'm not sure if this will be enough though for your repo; thus we could also use GitHub actions, this might be the better choice with 2000 [action minutes per month for free](https://github.com/pricing). I would be quite interested in adding this. Would you be okay with me doing that? If so, I might have to be a maintainer for a week. You could delete my maintainer status after I made the changes.

If you think this isn't necessary, feel free to just close this issue, no problem.

Thanks,
Rick

**Comment by piersdeseilligny** [comment]
@rickschubert sounds good! I don't really have any experience with this but you're right, it definitely wouldn't be a bad thing. I've added you as a collaborator.

**Comment by rickschubert** [comment]
I will close this ticket for now as well as my pull request. I wanted to open it as an issue to see how your opinion is but it actually isn't really an issue, more a feature suggestion. I will close my pull request https://github.com/piersdeseilligny/betterfountain/pull/73 for now. The pipeline itself was set up and working, but the tests aren't passing anymore - and nobody wants to merge in a pipeline with failing tests.

I had a glimpse at fixing the tests but since the screenplay statistics now also require the afterparser to run as well as the PDF creation, the tests can't run in isolation anymore and would have to be run on a VSCode host. I might look into it in my spare time out of personal interest but want to close it for now so as to not have a stale pull request on the repository and thereby maybe give the impression to other contributors that contributions wouldn't be welcome.
