### ISSUE TITLE
[feature request] Code folding for scenes

### ISSUE THREAD

**Issue by NQNStudios** [piersdeseilligny/betterfountain#77]
It would be nice if I could fold scenes like you can fold class/function bodies with most language extensions.

I could probably contribute a PR for this if need be. I see that [this](https://stackoverflow.com/a/50612239) is probably the quickest way to implement it, although based on experience trying to do the same thing with a similar language extension [here](https://github.com/DustinWoods/vscode-twee2-syntax/issues/7) I think we'll run into the same problem because the end of each region is going to be on the same line as the start of the next region.

So the way I would go about doing it would probably be with an optional comment syntax, like

```
/********************
 * Scene starts here *
 ********************/
```

where a line with stars followed by / is considered the start of a region, and a line with / followed by stars is considered the end of a region. Kind of weird but it just might work.

**Comment by piersdeseilligny** [comment]
@NQNStudios this should already be the case? You can fold scenes which are marked as scene headings (https://fountain.io/syntax#section-slug) and you can also fold [sections](https://fountain.io/syntax#section-sections). Is this not working for you?

**Comment by NQNStudios** [comment]
Damn. I missed the collapse button because it doesn't appear until the mouse hovers over it. Is there a VSCode setting to always show the collapse button next to the start of a collapsible region?

**Comment by NQNStudios** [comment]
[Found it!](https://stackoverflow.com/a/49731934) Thanks for your help, closing this issue now.
