### ISSUE TITLE
Reload" button never goes away

### ISSUE THREAD

**Issue by belzecue** [piersdeseilligny/betterfountain#8]
https://imgur.com/a/EfFTXGy

v1.1.2
Win10: after installing in VSC, "Reload" button never goes away.

NOTE: had to download the .vsix, because in-app install returned an error.

**Comment by piersdeseilligny** [comment]
This is odd, I reckon its probably a bug related to vscode rather than this extension. If anyone else runs into this issue can they please let me know?
