### ISSUE TITLE
Forcing a Line with "!" not working if line contains a word that is a transition

### ISSUE THREAD

**Issue by viegasfh** [piersdeseilligny/betterfountain#92]
Hi!

In Fountain we can force a line to be of type action if we precede it with an exclamation mark "!". Although the specs doesn't mention it, if the action line has spaces, the line should begin with a "!" as the first character. I tested this on Highland and I guess this is how it should work. Now, If I start a line with a "!" and the line has as first word ending in TO:, it prints both the "!" and treats the TO: as a transition. This should be rendered as action, respecting all the spaces.

Here is a screenshot of the issue highlighted in the source (fountain) and in the preview:

![image](https://user-images.githubusercontent.com/290857/98052456-96ae3a80-1e36-11eb-9752-a2f3c2a91426.png)

Here is the same text rendered in Highland:

![Highland Rendering](https://user-images.githubusercontent.com/290857/98052850-906c8e00-1e37-11eb-86e5-d0257e66246e.png)

Given that BetterFountain is using the Afterwriting renderer, I don't know if this could be fixed by you and then push it upstream to Afterwriting, or if I should report it on the Afterwriting repository.

Do let me know.

**Comment by viegasfh** [comment]
Looks like the issue went through. I had received an error when I published it.

**Comment by piersdeseilligny** [comment]
Thanks for the issue - this can actually be fixed by betterfountain, as it uses a fork of the afterwriting parser, with some fairly heavy modifications: all the parsing and rendering is done "in-house", despite initially being based on afterwriting. 
I'm really busy this week, but i'il look at fixing this asap!

**Comment by viegasfh** [comment]
Hi, Piers!

No rush. I have been using BetterFountain on a daily basis now. So, any bugs I find I'll report.

**Comment by viegasfh** [comment]
Perfect! Thanks a lot of taking the time to fix this.
