### ISSUE TITLE
Extension unresponsive

### ISSUE THREAD

**Issue by shauryashaurya** [piersdeseilligny/betterfountain#94]
- Issue Type: `Bug`
- Extension Name: `betterfountain`
- Extension Version: `1.6.11`
- OS Version: `Windows_NT x64 10.0.15063`
- VSCode version: `1.51.1`

VS Code keeps complaining that Better Fountain took too long to load.

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 10099,
		"activateCallTime": 10,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "piersdeseilligny.betterfountain",
				"_lower": "piersdeseilligny.betterfountain"
			},
			"activationEvent": "onLanguage:fountain"
		}
	},
	"runtimeErrors": []
}
```

**Comment by piersdeseilligny** [comment]
that's odd...  @shauryashaurya does this still occur if you disable this setting?

![image](https://user-images.githubusercontent.com/42496508/99671440-f0834700-2a69-11eb-891a-e221dca19439.png)

**Comment by shauryashaurya** [comment]
I tried this today and did not get the issue again.
Can you give me another day of testing?

**Comment by piersdeseilligny** [comment]
Sure no worries :) i won't close this issue yet then - let me know if you run into this problem again (or any other)

**Comment by piersdeseilligny** [comment]
@shauryashaurya have you run into this issue again?

**Comment by shauryashaurya** [comment]
I did not see this again, have been using it for the past couple of week. 
Thanks  a bunch for the quick solve! :)
