### ISSUE TITLE
Reference your wonderful extension to the fountain project

### ISSUE THREAD

**Issue by Tilix4** [piersdeseilligny/betterfountain#97]
Your extension is wonderful, and I didn't find it on the Fountain project apps, you must contact them to be referenced!

The apps page: https://fountain.io/apps

Contact the owner: https://prolost.com/contact (found with `Contact Us` from the apps page)

**Comment by piersdeseilligny** [comment]
Funny you should raise this, I was actually exchanging emails with Nima Yousefi about this yesterday :D hopefully it will be on the website in a few days

**Comment by Tilix4** [comment]
That's very good news !

**Comment by piersdeseilligny** [comment]
Done!
![image](https://user-images.githubusercontent.com/42496508/102140839-cbf77080-3e57-11eb-98a2-d1f4271b65f0.png)
